import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

interface Movie {
  name: string;
  slug: string;
  resource_url: string;
}

export const movies: Movie[] = [
  {
    name: "Arrival",
    slug: "arrival-2016",
    resource_url: "https://content.viaplay.se/pc-se/film/arrival-2016",
  },
  {
    name: "Love, Weddings & Other Disasters - Film online på Viaplay",
    slug: "love-weddings-and-other-disasters-2020",
    resource_url:
      "https://content.viaplay.se/pc-se/film/love-weddings-and-other-disasters-2020",
  },
  {
    name: "Kvinnan på tåget - Film online på Viaplay",
    slug: "kvinnan-pa-taget-2016",
    resource_url: "https://content.viaplay.se/pc-se/film/kvinnan-pa-taget-2016",
  },
];

export const moviesMap: Map<string, Movie> = movies.reduce(
  (previousValue: Map<string, Movie>, currentValue: Movie) => {
    return previousValue.set(currentValue.slug, currentValue);
  },
  new Map<string, Movie>()
);

interface MoviesProps {
  movies: Movie[];
}

const Home: NextPage<MoviesProps> = ({ movies }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        Movies:
        {movies.map((movie) => {
          return (
            <div key={movie.slug}>
              <Link href={"film/" + movie.slug}>
                <a>{movie.name}</a>
              </Link>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export const getStaticProps = async () => {
  return {
    props: {
      movies,
    },
  };
};

export default Home;
